#!/usr/bin/env python3
"""Monthly AIEL Monitor Brief draft, emailed to Magnus for review two weeks ahead.

Run by .github/workflows/monthly-brief-draft.yml on the 14th (and manually). Builds NEXT
month's brief (both languages) via build.py's BRIEF_MONTH_OVERRIDE, extracts the readable
text, and emails it to Magnus over Gmail SMTP using the GMAIL_APP_PASSWORD repo secret.
Nothing is published — Magnus reviews, replies "go", and the issue is posted to Substack.
"""
import os, re, html, smtplib, subprocess, calendar
from datetime import date
from email.mime.text import MIMEText
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TO = FROM = "mlodefalk@gmail.com"

# --- next month (roll Dec -> Jan) ---
t = date.today()
ny, nm = (t.year + 1, 1) if t.month == 12 else (t.year, t.month + 1)
mname = calendar.month_name[nm]
override = f"{ny}-{nm:02d}"

# --- build next month's brief (EN + SV) ---
env = {**os.environ, "BRIEF_MONTH_OVERRIDE": override}
subprocess.run(["python3", "build.py"], cwd=ROOT, env=env, check=True)


def brief_text(rel):
    s = (ROOT / rel).read_text(encoding="utf-8")
    m = re.search(r'<article class="briefsheet">(.*?)</article>', s, re.S)
    s = m.group(1) if m else s
    s = re.sub(r"<svg.*?</svg>", " [chart] ", s, flags=re.S)      # drop chart internals
    s = re.sub(r"<[^>]+>", " ", s)                                # strip remaining tags
    s = html.unescape(s)
    s = re.sub(r"[ \t]+", " ", s)
    s = re.sub(r"\n\s*\n\s*\n+", "\n\n", s)
    return s.strip()


en = brief_text("docs/monitor/brief/index.html")
sv = brief_text("docs/monitor/brief/sv/index.html")
bar = "=" * 60

body = f"""Draft of the AIEL Monitor Brief for {mname} {ny}, for your review before publication.

Auto-generated by the monthly GitHub Action. Read both versions; reply "go" (or with edits)
and Claude will publish it to Substack. Nothing is published automatically.

{bar}
ENGLISH
{bar}
{en}

{bar}
SVENSKA
{bar}
{sv}

{bar}
CHECK BEFORE PUBLISHING
{bar}
- Are the headline numbers current? (Some sources refresh on their own cadence.)
- Issue-1 content candidates from the 24 Jul 2026 rebuild (20-year arc / genAI share /
  title newcomers): lab-infrastructure/ai-monitor/notes/brief-issue1-content-candidates_2026-07-24.md
- Does this month's in-focus theme have its own chart yet, or is it using a placeholder?
  (See data/brief_calendar.yaml; themes leaning on Akavia need that source live.)
- Read the Swedish closely and flag anything that reads translated.
- Lab news at the bottom: still accurate, anything to add?

Live format reference: https://ai-econ-lab.github.io/monitor/brief/ (EN) and /sv/ (SV).
"""

msg = MIMEText(body, "plain", "utf-8")
msg["Subject"] = f"AIEL Monitor Brief draft — {mname} {ny} (for review)"
msg["From"], msg["To"] = FROM, TO

pw = os.environ["GMAIL_APP_PASSWORD"].replace(" ", "")   # app passwords display with spaces
with smtplib.SMTP("smtp.gmail.com", 587, timeout=60) as s:
    s.starttls()
    s.login(FROM, pw)
    s.send_message(msg)
print(f"Sent {mname} {ny} draft to {TO} ({len(en)} EN chars, {len(sv)} SV chars).")
