#!/usr/bin/env python3
"""Build data/livewindow.yaml from the ai-monitor JobStream live window.

WHY THIS EXISTS. `jobstream_ingest.py --emit-livewindow` calls itself "that path's first
half", and the second half was never built. The result was two independent stalls of the same
number:

  24 Jul -> 8 Aug   the site published 1.85 and 0.89 while the feed said 1.63 and 0.80
  12 Aug -> 17 Aug  the site published 12 Aug while the poll ingested ads every day

Both were repaired by hand-copying, which is why both happened. This script is the copy, and
the workflow that runs it is the thing that was actually missing.

It reads the JSON the ingester emits and writes a small generated YAML. The site's prose is
composed from that YAML at build time (see livewindow_block in build.py), so the sentence a
reader sees cannot disagree with the feed: the previous sentence carried "32,022", "1.57" and
"0.80" as typed characters, and updating `asof` alone would have advanced the date over three
frozen numbers, which is worse than being visibly stale.

Source root is $AI_MONITOR_ROOT, defaulting to the local checkout, so the same script serves a
laptop run and the scheduled workflow.

Run:  python3 scripts/refresh_livewindow.py
"""

import json
import os
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MONITOR_ROOT = Path(os.environ.get(
    "AI_MONITOR_ROOT",
    Path.home() / "Documents/Workspace/lab-infrastructure/ai-monitor"))
SRC = MONITOR_ROOT / "data" / "jobstream" / "livewindow.json"
OUT = ROOT / "data" / "livewindow.yaml"

# A window whose rows were scored under two different term-list definitions averages two
# instruments into one number. The emitter flags it; refusing it is this side's job, and
# nothing did that job before -- the 24 Jul window was 71% v1 and 29% v1.1, published as one
# figure with nothing saying so.
MAX_AGE_DAYS = 4


def main():
    if not SRC.exists():
        raise SystemExit(
            f"refresh_livewindow: {SRC} not found.\n"
            f"Set AI_MONITOR_ROOT to the ai-monitor checkout, or run\n"
            f"  python3 scripts/jobstream_ingest.py --emit-livewindow\n"
            f"in that repo first.")

    d = json.loads(SRC.read_text(encoding="utf-8"))

    if d.get("mixed_definitions"):
        raise SystemExit(
            "refresh_livewindow: the window spans more than one term-list definition "
            f"({d.get('off_definition_pct')}% off the dominant one). Publishing it would "
            "average two instruments into one number. Re-seed the store, then re-emit.")

    asof = datetime.strptime(d["asof"], "%d %b %Y").date()
    age = (date.today() - asof).days
    if age > MAX_AGE_DAYS:
        raise SystemExit(
            f"refresh_livewindow: livewindow.json is stamped {d['asof']}, {age} days old. "
            "The daily poll emits it; an old file means the emit step did not run, and "
            "republishing it would restate a stale number under a fresh build date.")
    if age < 0:
        raise SystemExit(f"refresh_livewindow: {d['asof']} is in the future; check the clock.")

    for k in ("n", "names_pct", "floor_pct"):
        if d.get(k) is None:
            raise SystemExit(f"refresh_livewindow: '{k}' is missing from {SRC.name}.")

    nlo, nhi = d["names_ci"]
    flo, fhi = d["floor_ci"]
    lines = [
        "# Generated by scripts/refresh_livewindow.py from the ai-monitor JobStream store.",
        "# Do not hand-edit: the next scheduled run overwrites it. The stable prose that",
        "# frames these numbers lives in monitor.yaml under livewindow.note.",
        f"asof: \"{d['asof']}\"",
        f"asof_iso: {asof.isoformat()}",
        f"window_days: {d['window_days']}",
        f"n: {d['n']}",
        f"names_pct: {d['names_pct']}",
        f"floor_pct: {d['floor_pct']}",
        f"names_ci: [{nlo}, {nhi}]",
        f"floor_ci: [{flo}, {fhi}]",
        f"generated_at: \"{d['generated_at']}\"",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"livewindow.yaml <- {d['asof']} (age {age}d): N={d['n']:,}, "
          f"names {d['names_pct']}% [{nlo}–{nhi}], floor {d['floor_pct']}% [{flo}–{fhi}]")


if __name__ == "__main__":
    main()
