#!/usr/bin/env python3
"""Build data/demand_by_sector.yaml from the ai-monitor pooled sector comparison.

    python3 scripts/refresh_demand_by_sector.py            # unit: raw records (as published)
    python3 scripts/refresh_demand_by_sector.py --distinct # the Monitor's unit

WHY (7 Oct 2026). The yaml said "Auto-generated by scripts/demand_by_sector.py", but no script
wrote it: it was assembled by hand from employer_counts_<Y>.json, whose AI advertisements came
from the July tier frame (an older, unnamed lexicon), and it carried no definition stamp. The
numbers now come from `demand_by_sector.py --pooled --def=<label>` in ai-monitor, which scores
every advertisement with the definition's own score() and stamps it; this script only formats.
check_vintages.py fails if the stamp is missing or is not the site's DEF_FP.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from monitor_root import MONITOR_ROOT, DEF_VERSION, DEF_FP  # noqa: E402

UNIT = "distinct" if "--distinct" in sys.argv else "raw"
LABEL = next((a.split("=", 1)[1] for a in sys.argv[1:] if a.startswith("--def=")), DEF_VERSION)
SRC = MONITOR_ROOT / "data" / "demand_by_sector" / f"demand_by_sector_pooled_{LABEL}_{UNIT}.json"
OUT = Path(__file__).resolve().parent.parent / "data" / "demand_by_sector.yaml"
MIN_AI = 100

NAMES = {
    "58-63": ("Information and communication", "Information och kommunikation"),
    "10-33": ("Manufacturing", "Tillverkning"),
    "69-75, 77-82, 95.1": ("Other services", "Övriga tjänsteföretag"),
    "35-39": ("Energy and recycling", "Energi och återvinning"),
    "45-47": ("Trade", "Handel"),
    "49-53": ("Transport and storage", "Transport och magasinering"),
    "68": ("Real estate", "Fastighetsverksamhet"),
    "41-43": ("Construction", "Byggverksamhet"),
    "55-56": ("Accommodation and food", "Hotell och restaurang"),
}


def main():
    if not SRC.exists():
        raise SystemExit(f"refresh_demand_by_sector: {SRC} not found. In ai-monitor run\n"
                         f"  python3 scripts/demand_by_sector.py --pooled --def={LABEL} --unit={UNIT}")
    d = json.loads(SRC.read_text(encoding="utf-8"))
    if d.get("definition_fp") != DEF_FP:
        print(f"NOTE: built on {d.get('definition_label')} {d.get('definition_fp')}; the site "
              f"publishes {DEF_VERSION} {DEF_FP}. check_vintages.py will fail until they agree.")
    rows = []
    for code, g in d["groups"].items():
        en, sv = NAMES[code]
        rows.append({"code": code, "en": en, "sv": sv, "demand": round(100 * g["ai"] / g["ads"], 2),
                     "ai": g["ai"], "ads": g["ads"], "firms": g["firms"],
                     "est": g["ai"] >= MIN_AI})
    rows.sort(key=lambda r: -r["demand"])
    n_est = sum(r["est"] for r in rows)
    unit_txt = "raw records" if UNIT == "raw" else "distinct advertisements"
    lines = [
        "# AI demand by industry, from OUR advertisement corpus, cut on SCB's own industry groups.",
        "# Generated by scripts/refresh_demand_by_sector.py from ai-monitor",
        f"# data/demand_by_sector/{SRC.name}. DO NOT hand-edit.",
        "#",
        "# POPULATION, and it is not SCB's. These are advertisements from employers among the 1,000",
        f"# largest advertisers of {d['rank_year']}, pooled over {d['years']}, business sector only. SCB's adoption",
        "# figure is all enterprises with ten or more employees. The two are put side by side, never",
        "# subtracted, and the difference is stated wherever either number appears.",
        "#",
        f"# A group is marked estimable: false below {MIN_AI} AI advertisements. {n_est} of {len(rows)} are.",
        "meta:",
        '  indicator: "Advertisements requiring a named AI skill, share of all advertisements"',
        '  unit: "% of advertisements"',
        f'  counting_unit: "{unit_txt}"',
        '  source: "AIEL Monitor, Platsbanken via JobTech; industry from Bolagsverket HVD"',
        f'  years: "{d["years"]}"',
        f"  min_ai_ads: {MIN_AI}",
        f"  ads_mapped: {d['ads_mapped']}",
        f"  ads_total: {d['ads_total']}",
        f"  coverage_pct: {round(100 * d['ads_mapped'] / d['ads_total'], 1)}",
        f"  outside_scb_frame: {d['outside_scb_frame']}",
        f"  employers_unresolved_ads: {d['employers_unresolved_ads']}",
        f"  definition: {d['definition_label']}",
        f"  definition_fp: {d['definition_fp']}",
        "sectors:",
    ]
    for r in rows:
        lines.append(f'  - {{code: "{r["code"]}", name_en: "{r["en"]}", name_sv: "{r["sv"]}", '
                     f'demand: {r["demand"]}, ai_ads: {r["ai"]}, ads: {r["ads"]}, '
                     f'firms: {r["firms"]}, estimable: {"true" if r["est"] else "false"}}}')
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"demand_by_sector.yaml <- {SRC.name}: {len(rows)} groups, {n_est} estimable")


if __name__ == "__main__":
    main()
