#!/usr/bin/env python3
"""Refresh Swedish POPULATION genAI use from SCB, for the Adoption module.

    python3 scripts/refresh_population_ai.py        # writes data/population_ai.yaml

Why this exists. The Adoption module measures firms (Eurostat, SCB's enterprise ICT
survey) and one slice of workers (Akavia, a professional-union panel). It has had nothing
representative of the population. SCB publishes exactly that: "Befolkningens it-användning"
now carries a dedicated AI area (LE0108Q) with genAI use for ages 16–74, by sex and age,
with margins of error — a probability sample and official statistics, which is a stronger
instrument than anything else in the module.

This is the PUBLIC aggregate. The lab separately holds BITA microdata in MONA
(ORU-MICRO-AI, individual-level genAI use, purpose and non-use reasons); that is red-zone
research data and must never reach this site. The two are different objects with the same
origin — use this file for the Monitor and MONA for papers.

Tables:
  LE0108T82  Använt generativa AI-verktyg — share of persons. Clean, both waves, used.
  LE0108T83  Syfte (professional / education / private) — NOT written as a time series.
             The 2024 and 2025 waves cannot share a base: the three purposes sum to 41%
             against 28% total use in 2024 and 66% against 42% in 2025, and "formal
             education" falls 20% -> 11% while "private" rises 8% -> 34%. Multiple-response
             explains sums above the total, but not a halving beside a quadrupling. Until
             SCB's base is confirmed, only the 2025 cross-section is emitted, flagged.

Stdlib only. api.scb.se is on the lab allowlist.
"""
from __future__ import annotations

import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "population_ai.yaml"
BASE = "https://api.scb.se/OV0104/v1/doris/sv/ssd/LE/LE0108/LE0108Q"

AGES = ["16-24", "25-34", "35-44", "45-54", "55-64", "65-74"]
AGE_LABEL = {"16-24": "16–24", "25-34": "25–34", "35-44": "35–44",
             "45-54": "45–54", "55-64": "55–64", "65-74": "65–74"}


def post(table: str, query: list) -> dict:
    req = urllib.request.Request(
        f"{BASE}/{table}",
        data=json.dumps({"query": query, "response": {"format": "json"}}).encode(),
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read())


def num(v):
    """SCB writes '..' for suppressed cells; keep them out of the yaml as null."""
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def main() -> None:
    # ── headline + age gradient + sex, both waves
    d = post("LE0108T82", [
        {"code": "AnvInternet", "selection": {"filter": "item", "values": ["1280"]}},
        {"code": "Kon", "selection": {"filter": "item", "values": ["1", "2", "1+2"]}},
        {"code": "Redovisningsgrupp",
         "selection": {"filter": "item", "values": ["tot16-74"] + AGES}},
        {"code": "ContentsCode",
         "selection": {"filter": "item", "values": ["000007L5", "000007LA"]}},
    ])
    cell = {}
    for e in d["data"]:
        _, sex, grp, yr = e["key"]
        cell[(grp, yr, sex)] = (num(e["values"][0]), num(e["values"][1]))
    years = sorted({k[1] for k in cell})
    latest, first = years[-1], years[0]

    def g(grp, yr, sex="1+2"):
        return cell.get((grp, yr, sex), (None, None))

    tot_l, moe_l = g("tot16-74", latest)
    tot_f, _ = g("tot16-74", first)
    men_l, _ = g("tot16-74", latest, "1")
    wom_l, _ = g("tot16-74", latest, "2")
    men_f, _ = g("tot16-74", first, "1")
    wom_f, _ = g("tot16-74", first, "2")

    L = [
        "# Swedish POPULATION genAI use — Adoption module, population level.",
        "# Generated by scripts/refresh_population_ai.py from SCB Befolkningens it-användning",
        "# (LE0108Q). DO NOT hand-edit; rerun the script, then build.py.",
        "#",
        "# This is the public aggregate. The lab's BITA microdata in MONA is red-zone and",
        "# must never appear here; see the script header.",
        "meta:",
        '  indicator: "Persons who have used generative AI tools"',
        '  unit: "% of persons aged 16–74"',
        '  source: "SCB, Befolkningens it-användning (LE0108T82)"',
        '  url: "https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__LE__LE0108__LE0108Q/"',
        f'  year: {latest}',
        f'  first_year: {first}',
        '  design: "probability sample, official statistics; margins of error published"',
        '  reference_period: "first quarter of the survey year"',
        f'  headline: {tot_l:g}',
        f'  headline_moe: {moe_l:g}',
        f'  headline_first: {tot_f:g}',
        f'  men: {men_l:g}',
        f'  women: {wom_l:g}',
        f'  men_first: {men_f:g}',
        f'  women_first: {wom_f:g}',
        "by_age:",
    ]
    for a in AGES:
        cur, moe = g(a, latest)
        prev, _ = g(a, first)
        if cur is None:
            continue
        L.append(f'  - {{group: "{AGE_LABEL[a]}", adoption: {cur:g}, moe: {moe:g}, '
                 f'prev: {prev if prev is not None else "null"}}}')

    # ── purpose, latest wave only (see header for why not a series)
    p = post("LE0108T83", [
        {"code": "SyftAnd", "selection": {"filter": "item",
                                          "values": ["ProfarbAnd", "FormUtb", "PrivAnd"]}},
        {"code": "Kon", "selection": {"filter": "item", "values": ["1+2"]}},
        {"code": "Redovisningsgrupp", "selection": {"filter": "item", "values": ["tot16-74"]}},
        {"code": "ContentsCode", "selection": {"filter": "item", "values": ["000007LC"]}},
    ])
    lab = {"ProfarbAnd": "professional or work-related", "FormUtb": "formal education",
           "PrivAnd": "private"}
    L += ["purpose_latest:",
          f"  # {latest} cross-section only. Multiple response, share of ALL persons 16–74.",
          "  # The 2024 wave is deliberately omitted: its base is not reconcilable with this",
          "  # one (purposes sum to 41 against 28% total use in 2024, 66 against 42 in 2025;",
          "  # formal education halves while private quadruples). Confirm SCB's base before",
          "  # using either wave as a series.",
          f"  year: {latest}",
          "  shares:"]
    for e in p["data"]:
        if e["key"][3] != latest:
            continue
        v = num(e["values"][0])
        if v is not None:
            L.append(f'    - {{purpose: "{lab[e["key"][0]]}", pct: {v:g}}}')

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {latest} headline {tot_l:g}% (±{moe_l:g}), "
          f"{first} {tot_f:g}%; {len(AGES)} age groups; purpose {latest} only")


if __name__ == "__main__":
    main()
