#!/usr/bin/env python3
"""Build data/monthly_demand.yaml from the ai-monitor monthly share series.

The published AI-in-Demand series is annual, which makes the Monitor read as a yearbook. The
monthly numerator was always free (every candidate extract carries a publication date); the
denominator arrived with the Phase B pass over the archives, which reproduces the published
annual series exactly when grouped by archive file. See
`lab-infrastructure/ai-monitor/scripts/build_monthly_series.py` for the reconciliation.

Emits the raw monthly share plus a 12-month trailing mean. The raw line carries the seasonality
(Swedish hiring collapses in July and again in December) and the trailing mean carries the
trend; showing only the smoothed line would hide how noisy a single month is.

Run:  python3 scripts/refresh_monthly_demand.py
"""

import csv
from pathlib import Path

# _v11 is the DISTINCT-advertisement series (the v1.1 freeze made the distinct advertisement
# the published unit); the unsuffixed file is the raw RECORD series kept alongside it as the
# robustness line. Both totals are emitted, because the site states both and had been typing
# them: "8.1M distinct public job ads (11.2M ad records)" was hand-written in two places and
# could not disagree with its own data anywhere a build could notice.
SRC = (Path.home() / "Documents/Workspace/lab-infrastructure/ai-monitor"
       / "data/free_cuts/monthly_ai_share_v11.csv")
SRC_RECORDS = SRC.with_name("monthly_ai_share.csv")
OUT = Path(__file__).resolve().parent.parent / "data" / "monthly_demand.yaml"
WINDOW = 12


def main():
    rows = [r for r in csv.DictReader(SRC.open(encoding="utf-8"))
            if r["thin"] != "1" and r["partial"] != "1"]
    ym = [r["year_month"] for r in rows]
    ai = [float(r["ai_any_pct"]) for r in rows]
    floor = [float(r["floor_pct"]) for r in rows]
    ads = [int(r["ads"]) for r in rows]
    rec_rows = [r for r in csv.DictReader(SRC_RECORDS.open(encoding="utf-8"))
                if r["thin"] != "1" and r["partial"] != "1"]
    total_records = sum(int(r["ads"]) for r in rec_rows)
    if total_records < sum(ads):
        raise SystemExit("refresh_monthly_demand: the record series is smaller than the distinct "
                         "series. The two source files have been swapped.")

    def trailing(v):
        out = []
        for i in range(len(v)):
            lo = max(0, i - WINDOW + 1)
            out.append(round(sum(v[lo:i + 1]) / (i - lo + 1), 4))
        return out

    ai_ma, floor_ma = trailing(ai), trailing(floor)
    peak = max(range(len(ai)), key=lambda i: ai[i])
    ymax = max(1, int(max(ai)) + 1)

    lines = ["# Generated by scripts/refresh_monthly_demand.py. Do not hand-edit.",
             "meta:",
             f"  first: {ym[0]}", f"  last: {ym[-1]}", f"  n_months: {len(ym)}",
             f"  ymax: {ymax}", f"  window: {WINDOW}",
             f"  peak_month: {ym[peak]}", f"  peak_value: {ai[peak]:.2f}",
             f"  last_value: {ai[-1]:.2f}", f"  last_ma: {ai_ma[-1]:.2f}",
             f"  last_floor_ma: {floor_ma[-1]:.2f}",
             f"  total_ads: {sum(ads)}",
             f"  total_records: {total_records}",
             "  source: JobTech historical job ads (Arbetsförmedlingen), CC0",
             "series:"]
    for i, m in enumerate(ym):
        lines.append(f"  - {{m: '{m}', ai: {ai[i]:.4f}, ai_ma: {ai_ma[i]:.4f}, "
                     f"floor: {floor[i]:.4f}, floor_ma: {floor_ma[i]:.4f}, ads: {ads[i]}}}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"monthly_demand.yaml: {len(ym)} months, {ym[0]} to {ym[-1]}")
    print(f"  peak single month: {ym[peak]} at {ai[peak]:.2f}%")
    print(f"  latest: {ym[-1]} {ai[-1]:.2f}% raw, {ai_ma[-1]:.2f}% on the {WINDOW}-month mean")
    print(f"  ads behind the series: {sum(ads):,} distinct, {total_records:,} records")


if __name__ == "__main__":
    main()
