#!/usr/bin/env python3
"""Build data/vocabulary.yaml: what words the AI ads actually use, era by era.

WHY THIS EXISTS. The standing objection to any long AI-in-Demand series is that a term list
written in 2026 is being applied backwards, so the early years are measured with today's
vocabulary and the growth is an artefact. This chart answers it with the data: the ads of 2006
are dominated by words almost nobody uses now (data mining, expert systems), and the generative
vocabulary is absent until 2022. The list is not anachronistic; the language turned over.

TERMS ARE DATE-GATED. Four product names in the frozen v1 list match ads published before the
product existed (gemini, claude, copilot, and chatgpt on a shorter fuse). Ungated, this chart
would show a reader "gemini, 2006", which is a false positive rather than a fact about 2006. See
`ai-monitor/notes/v1_1-fixlist_anachronisms_2026-07-30.md`; the gate here is for DISPLAY only and
changes no published series, because v1 is frozen.

THE COUNTING UNIT IS EMITTED HERE, NOT PATCHED INTO THE OUTPUT. On 31 July the v1.1 migration
hand-edited `data/vocabulary.yaml`'s source line to claim "distinct advertisements" while every
number in the file was still a raw-record count, and this script would have silently reverted
the claim on its next run. The chart is now built from `term_composition.csv`, which counts each
advertisement once, and the source string below states that because the generator says so.
Never hand-edit the output: the header says not to, and that is exactly how the two disagreed.

Run:  python3 scripts/refresh_vocabulary.py
"""
import csv
from pathlib import Path

SRC = (Path.home() / "Documents/Workspace/lab-infrastructure/ai-monitor"
       / "data/diagnostics/term_composition.csv")
OUT = Path(__file__).resolve().parent.parent / "data" / "vocabulary.yaml"

# Two classes are gated for display. ANACHRONISMS: product names matching ads published before
# the product existed. POLYSEMY: ordinary words that later became AI terms, where the early hits
# are the ordinary sense. "finjustering" is plain Swedish for mechanical fine-tuning, "prompting"
# had a clinical and pedagogical sense, "gpt" is also a lab test and a disk partition table, and
# "llm" is also a Master of Laws. Checked: in 2023-2026 "llm" sits in software and research
# occupations, so the modern hits are the language-model sense and are kept.
GATE = {"gemini": 2023, "claude": 2023, "copilot": 2023, "chatgpt": 2022,
        "llama": 2023, "mistral": 2023, "sora": 2024, "grok": 2023,
        "prompting": 2022, "finjustering": 2022, "gpt": 2022, "llm": 2022}
FAMILY = [
    ("genai", ["llm", "large language", "generativ", "generative", "chatgpt", "gpt",
               "transformer", "prompt", "copilot", "gemini", "claude", "finjustering",
               "diffusion", "hallucin"]),
    ("ml", ["machine learning", "maskininlärning", "deep learning", "djupinlärning", "neural",
            "computer vision", "datorseende", "machine vision", "tensorflow", "pytorch",
            "scikit", "boosting", "clustering", "mlops", "image processing", "bildanalys",
            "natural language processing", "språkteknologi", "sensor fusion", "random forest",
            "reinforcement", "förstärkningsinlärning", "gradient"]),
    ("early", ["data mining", "datautvinning", "expertsystem", "expert system",
               "språkbehandling", "fuzzy", "genetisk algoritm", "beslutsstöd"]),
    ("generic", ["artificiell intelligens", "artificial intelligence", "ai/ml", "a.i."]),
]


def family(term):
    t = f" {term.lower()} "
    for name, keys in FAMILY:
        if any(k in t for k in keys):
            return name
    return "generic" if t.strip() in {"ai", "ki"} else "other"


rows = list(csv.DictReader(SRC.open(encoding="utf-8")))
cols = [c for c in rows[0] if c not in ("term", "total")]
series, other_max = [], 0
for c in cols:
    agg, tot = {}, 0
    for r in rows:
        n = int(r[c] or 0)
        y = int(c[:4])
        if not n or any(g in r["term"].lower() and y < yr for g, yr in GATE.items()):
            continue
        agg[family(r["term"])] = agg.get(family(r["term"]), 0) + n
        tot += n
    if not tot:
        continue
    pct = {k: round(100 * v / tot, 2) for k, v in agg.items()}
    other_max = max(other_max, pct.get("other", 0))
    series.append({"p": c, "early": pct.get("early", 0), "ml": pct.get("ml", 0),
                   "generic": pct.get("generic", 0), "genai": pct.get("genai", 0),
                   "other": pct.get("other", 0), "n": tot})

first, last = series[0], series[-1]
lines = ["# Generated by scripts/refresh_vocabulary.py. Do not hand-edit.",
         "meta:",
         f"  first: {first['p']}", f"  last: {last['p']}", f"  n_periods: {len(series)}",
         f"  early_first: {first['early']}", f"  early_last: {last['early']}",
         f"  genai_last: {last['genai']}", f"  ml_peak: {max(s['ml'] for s in series)}",
         f"  other_max: {round(other_max, 1)}",
         f"  total_term_hits: {sum(s['n'] for s in series)}",
         "  source: JobTech historical job ads (Arbetsförmedlingen), CC0, frozen v1.1 term "
         "list, distinct advertisements",
         "series:"]
for s in series:
    lines.append(f"  - {{p: '{s['p']}', early: {s['early']}, ml: {s['ml']}, "
                 f"generic: {s['generic']}, genai: {s['genai']}, other: {s['other']}, n: {s['n']}}}")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"vocabulary.yaml: {len(series)} periods, {first['p']} to {last['p']}")
print(f"  early-era words   {first['early']:.0f}% -> {last['early']:.1f}%")
print(f"  generative words  {first['genai']:.1f}% -> {last['genai']:.1f}%")
print(f"  unclassified peaks at {other_max:.1f}%")
