#!/usr/bin/env python3
"""Same-months comparison for the October 2026 brief: the latest part-year against the same
months one year earlier, for every measure the brief's chart shows.

Why (29 Sep 2026): two reviewers (a Harford-style and a Depenbusch-style read) flagged that the
brief compared a January-June 2026 share with full-year 2025. Hiring is seasonal, so the fair
comparison is the same months. Reads the monthly outputs of the bulk series the site claims
(monitor_root.bulk_dir()), distinct advertisements, and writes data/washing_samemonths.yaml.

Arithmetic as in build.py washing_series(): ceiling = whole-text + CEIL_BAND_SHARE x bare-only;
AI talk (grey) = (1 - CEIL_BAND_SHARE) x bare-only; every mention = whole-text + bare-only.
"""
import glob, re, sys
from pathlib import Path
import pandas as pd
sys.path.insert(0, str(Path(__file__).parent))
from monitor_root import monitor_root as root, bulk_dir, DEF_VERSION   # noqa: E402

SHARE = 0.128   # must equal build.py CEIL_BAND_SHARE
OUT = Path(__file__).resolve().parent.parent / "data" / "washing_samemonths.yaml"

def main():
    d = root() / "data" / bulk_dir()
    # Strict filename match, never a bare wildcard: iCloud drops "name 2.csv" conflict copies
    # beside the originals and a wildcard reads them too, doubling the advertisement counts
    # (measured on bulk_v16, 8 Oct 2026: 478,714 instead of 239,357 for Jan-Jun 2026).
    files = sorted(f for f in glob.glob(str(d / "v11_monthly_*.csv"))
                   if re.fullmatch(r"v11_monthly_\d{4}(-Q[1-4])?\.csv", Path(f).name))
    m = (pd.concat([pd.read_csv(f) for f in files]).groupby("month").sum(numeric_only=True))
    last = max(x for x in m.index if m.loc[x, "total_dd"] > 1000)      # last substantial month
    yr, mo = int(last[:4]), int(last[5:7])
    cur = [f"{yr}-{k:02d}" for k in range(1, mo + 1)]
    prev = [f"{yr - 1}-{k:02d}" for k in range(1, mo + 1)]
    def block(months):
        r = m.loc[m.index.isin(months)].sum(); T = r.total_dd
        wt, fl = r.ai_any_dd / T * 100, r.floor_dd / T * 100
        bd = (r.bare_broad_dd - r.ai_any_dd) / T * 100
        return {"ads": int(T), "floor": round(fl, 3), "ceiling": round(wt + SHARE * bd, 3),
                "bare": round(bd, 3), "talk": round((1 - SHARE) * bd, 3), "all": round(wt + bd, 3)}
    c, p = block(cur), block(prev)
    lines = [f"# Generated by scripts/refresh_washing_samemonths.py from {bulk_dir()} ({DEF_VERSION}). Do not hand-edit.",
             f"months: {mo}", f"year: {yr}"]
    for k, b in (("current", c), ("previous", p)):
        lines.append(f"{k}: {{" + ", ".join(f"{a}: {v}" for a, v in b.items()) + "}")
    # Occupation split (29 Sep 2026, on an Autor-style review): the share of AI demand (up to the
    # ceiling) and of the floor that is OUTSIDE ICT occupations (SSYK 25). SSYK is carried from
    # 2020 only. The ceiling correction is the pooled share, applied per occupation.
    s = pd.read_csv(d / "derived" / "series_ssyk4.csv", dtype={"ssyk4": str})
    s = s[s.ssyk4.notna()].copy()
    s["per"] = s.year.astype(str).str[:4]
    s["ict"] = s.ssyk4.str.startswith("25")
    s["ceil"] = s.ai_any_dd + SHARE * (s.bare_broad_dd - s.ai_any_dd)
    def outside(per, col):
        g = s[s.per == per]
        return round(100 * g.loc[~g.ict, col].sum() / g[col].sum(), 1)
    first = min(s.per)
    lines.append(f"nonict: {{first_year: {first}, ceiling_first: {outside(first, 'ceil')}, "
                 f"ceiling_now: {outside(str(yr), 'ceil')}, floor_first: {outside(first, 'floor_dd')}, "
                 f"floor_now: {outside(str(yr), 'floor_dd')}}}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT.read_text())

if __name__ == "__main__":
    main()
