#!/usr/bin/env python3
"""Build data/job_quality.yaml from the ai-monitor job-quality series.

Source: `lab-infrastructure/ai-monitor/scripts/build_job_quality.py`, which reads the structured
job-condition fields collected by the Phase B pass.

Restricted to 2018 onwards and to complete calendar years, for two reasons that are both
properties of the source rather than of the labour market:

  - Before 2018 the working-hours field offers 'heltid/deltid' as a third option, taken by 26 to
    46 per cent of ads before 2012 and by nobody after 2017. Those ads say the employer will
    accept either, so they are evidence about neither.
  - `employment_type` is not populated at all before 2018.
  - The current year is a part year, and summer-job ads are posted in spring, so a January to
    June slice over-weights them and is not comparable with a full year.

Run:  python3 scripts/refresh_job_quality.py
"""

import csv
import json
from pathlib import Path

from monitor_root import MONITOR_ROOT

SRC = (MONITOR_ROOT
       / "data/free_cuts/job_quality_v11.csv")
OUT = Path(__file__).resolve().parent.parent / "data" / "job_quality.yaml"
PROV = SRC.with_name("job_quality_v11.provenance.json")
FIRST = 2018


def main():
    # 7 Oct 2026: the series names its definition. Until then the CSV was built from a
    # hard-coded bulk_v11 and job_quality.yaml said nothing about which definition it was on.
    if not PROV.exists():
        raise SystemExit(f"refresh_job_quality: {PROV.name} missing. Rebuild with "
                         f"build_job_quality_v11.py --bulk=<the published bulk dir>.")
    prov = json.loads(PROV.read_text(encoding="utf-8"))
    if not prov.get("definition_fp") or prov.get("version", "UNNAMED") == "UNNAMED":
        raise SystemExit(f"refresh_job_quality: {PROV.name} names no frozen definition: {prov}")
    rows = list(csv.DictReader(SRC.open(encoding="utf-8")))
    by = {(r["year"], r["group"]): r for r in rows}
    years = sorted({r["year"] for r in rows if int(r["year"]) >= FIRST})
    # drop the part year: the last year present is complete only if a later one exists
    complete = years[:-1]

    series = []
    for y in complete:
        a, o = by[(y, "ai")], by[(y, "other")]
        series.append({
            "year": int(y),
            "ft_ai": float(a["full_time_pct"]), "ft_other": float(o["full_time_pct"]),
            "pm_ai": float(a["permanent_pct"]), "pm_other": float(o["permanent_pct"]),
            "rg_ai": float(a["regular_pct"]), "rg_other": float(o["regular_pct"]),
            "n_ai": int(a["ads"]),
        })
    for r in series:
        r["ft_gap"] = round(r["ft_ai"] - r["ft_other"], 2)
        r["pm_gap"] = round(r["pm_ai"] - r["pm_other"], 2)
        r["rg_gap"] = round(r["rg_ai"] - r["rg_other"], 2)

    first, last = series[0], series[-1]
    flip = next((r["year"] for r in series if r["pm_gap"] < 0), None)
    lo = min(min(r["ft_gap"], r["pm_gap"], r["rg_gap"]) for r in series)
    hi = max(max(r["ft_gap"], r["pm_gap"], r["rg_gap"]) for r in series)

    lines = ["# Generated by scripts/refresh_job_quality.py. Do not hand-edit.",
             "meta:",
             f"  first_year: {first['year']}", f"  last_year: {last['year']}",
             f"  ft_gap_first: {first['ft_gap']}", f"  ft_gap_last: {last['ft_gap']}",
             f"  pm_gap_first: {first['pm_gap']}", f"  pm_gap_last: {last['pm_gap']}",
             f"  rg_gap_first: {first['rg_gap']}", f"  rg_gap_last: {last['rg_gap']}",
             f"  pm_flip_year: {flip if flip else 'null'}",
             f"  ymin: {int(lo) - 2}", f"  ymax: {int(hi) + 3}",
             f"  n_ai_last: {last['n_ai']}",
             f"  definition: {prov['version']}",
             f"  definition_fp: {prov['definition_fp']}",
             f"  source: JobTech historical job ads (Arbetsförmedlingen), CC0, frozen {prov['version']} "
             f"term list, distinct advertisements",
             "series:"]
    for r in series:
        lines.append(
            f"  - {{year: {r['year']}, ft_gap: {r['ft_gap']}, pm_gap: {r['pm_gap']}, "
            f"rg_gap: {r['rg_gap']}, ft_ai: {r['ft_ai']}, ft_other: {r['ft_other']}, "
            f"pm_ai: {r['pm_ai']}, pm_other: {r['pm_other']}, rg_ai: {r['rg_ai']}, "
            f"rg_other: {r['rg_other']}, n_ai: {r['n_ai']}}}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"job_quality.yaml: {first['year']} to {last['year']}")
    print(f"  full-time gap  {first['ft_gap']:+.1f}pp -> {last['ft_gap']:+.1f}pp")
    print(f"  permanent gap  {first['pm_gap']:+.1f}pp -> {last['pm_gap']:+.1f}pp"
          + (f" (turns negative in {flip})" if flip else ""))
    print(f"  regular   gap  {first['rg_gap']:+.1f}pp -> {last['rg_gap']:+.1f}pp")


if __name__ == "__main__":
    main()
