#!/usr/bin/env python3
"""Build data/governance.yaml: demand for AI-governance and compliance roles.

The `adjacent` band has been computed in every annual build since the v1 freeze and has never
been shown. It counts ads that sit in AI's compliance and policy penumbra (AI Act, AI governance,
model risk, algorithmic accountability) rather than asking for an AI skill as such, which is why
it is a band of its own and not part of the headline series.

It is the fastest-growing thing in the whole build: zero until 2018, 169 in the whole of 2025,
and 199 in the first half of 2026 alone.

Run:  python3 scripts/refresh_governance.py
"""
import csv
from pathlib import Path

SRC = (Path.home() / "Documents/Workspace/lab-infrastructure/ai-monitor"
       / "data/bulk_v12/derived/series_annual.csv")
OUT = Path(__file__).resolve().parent.parent / "data" / "governance.yaml"

rows = list(csv.DictReader(SRC.open(encoding="utf-8")))
full, part = {}, {}
for r in rows:
    y = r["year"]
    (part if "-" in y else full)[y] = (int(r["adjacent"] or 0), int(r["ai_any"] or 0))
years = sorted(full)
h1 = [v for k, v in part.items() if k.startswith("2026")]
h1_adj, h1_ai = sum(a for a, _ in h1), sum(b for _, b in h1)

series = [{"year": int(y), "n": full[y][0],
           "pct_of_ai": round(100 * full[y][0] / full[y][1], 2) if full[y][1] else 0}
          for y in years if int(y) >= 2018]
last = series[-1]
lines = ["# Generated by scripts/refresh_governance.py. Do not hand-edit.",
         "meta:",
         f"  first_year: {series[0]['year']}", f"  last_year: {last['year']}",
         f"  last_n: {last['n']}", f"  last_pct: {last['pct_of_ai']}",
         f"  h1_2026_n: {h1_adj}",
         f"  h1_2026_pct: {round(100 * h1_adj / h1_ai, 2) if h1_ai else 0}",
         f"  ymax: {max(h1_adj, max(s['n'] for s in series)) }",
         "  source: JobTech historical job ads (Arbetsförmedlingen), CC0",
         "series:"]
for s in series:
    lines.append(f"  - {{year: {s['year']}, n: {s['n']}, pct_of_ai: {s['pct_of_ai']}}}")
lines.append(f"  - {{year: 2026, n: {h1_adj}, pct_of_ai: "
             f"{round(100 * h1_adj / h1_ai, 2) if h1_ai else 0}, partial: true}}")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"governance.yaml: {series[0]['year']}-{last['year']} plus 2026 H1")
for s in series:
    print(f"   {s['year']}  {s['n']:>4}  {s['pct_of_ai']:>5.2f}% of AI ads")
print(f"   2026H1 {h1_adj:>4}  {100*h1_adj/h1_ai:>5.2f}%  (half a year, already above all of {last['year']})")
