#!/usr/bin/env python3
"""Build data/occupation_tiers.yaml: who the AI is for, by occupation.

WHY THIS EXISTS. Until now it did not, and that was the problem. occupation_tiers.yaml was the
last hand-maintained data file on the Monitor: no generator, no "Generated by" header, one
commit, and its numbers transcribed by hand from tier_by_occupation.csv. Two consequences had
already landed. First, when the v1.1 freeze moved the Monitor to distinct advertisements, this
file could not follow, so its caption said "advertisements" over counts of ad RECORDS. Second,
six of its thirteen English occupation names existed nowhere else in the codebase; they were
invented at transcription time, and one of them ("Electrical engineers" for SSYK 2143) collides
with a different label already in use for 3113.

refresh_occupations.py hit the same class of bug from the same cause -- its docstring records
that it "was hand-maintained, which is why it still carried the v1 national figure after the
v1.1 freeze moved it" -- and the fix there was to generate it with an explicit name table. This
is that fix, applied to the other file.

WHAT THE THRESHOLD DOES. MIN_ADS lives here, in code, rather than as an assertion in the yaml.
That matters this time: on distinct advertisements three occupations that cleared 25 records
(marketing analysts 36, customer service 27, chemists 26) no longer clear 25 advertisements
(23, 24, 23). They leave the table. Showing them on a thinner base than the caption claims is
exactly the kind of quiet drift the hand-maintained file allowed.

Run:  python3 scripts/refresh_occupation_tiers.py
"""
import csv
from pathlib import Path

import yaml

from monitor_root import MONITOR_ROOT
from labels import shorten  # noqa: E402

SRC = (MONITOR_ROOT
       / "data/free_cuts/tier_by_occupation.csv")          # distinct advertisements
OUT = Path(__file__).resolve().parent.parent / "data" / "occupation_tiers.yaml"

YEAR = "2025"
MIN_ADS = 25

# Our English renderings of the employment service's Swedish occupational labels, kept
# explicit so a name cannot silently change between builds. An unlisted label falls through
# to the Swedish original, which is visible and fixable, rather than to a guess.
# Shared vocabulary with refresh_occupations.py's EN table wherever the label overlaps.
EN = {
    "Mjukvaru- och systemutvecklare m.fl.": "Software and systems developers",
    "Doktorander": "Doctoral students",
    "Forskarassistenter m.fl.": "Research assistants",
    "Övriga IT-specialister": "Other IT specialists",
    "Ingenjörer och tekniker inom elektroteknik": "Electrical engineers and technicians",
    "Systemanalytiker och IT-arkitekter m.fl.": "Systems analysts and IT architects",
    "Universitets- och högskolelektorer": "University lecturers",
    "Medicinska sekreterare; vårdadministratörer m.fl.": (
        "Medical secretaries and care administrators"),
    "Civilingenjörsyrken inom maskinteknik": "Mechanical engineers",
    # 2143, distinct from 3113 above: engineers rather than engineers and technicians.
    "Civilingenjörsyrken inom elektroteknik": "Electrical engineers (graduate)",
    "Övriga civilingenjörsyrken": "Other graduate engineers",
    "Marknadsanalytiker och marknadsförare m.fl.": "Marketing analysts and marketers",
    "Kundtjänstpersonal": "Customer service staff",
    "Kemister": "Chemists",
    "IT-säkerhetsspecialister": "IT security specialists",
    "Informatörer; kommunikatörer och PR-specialister": (
        "Communications and PR specialists"),
}

CAVEAT = (
    f"Occupations with at least {MIN_ADS} distinct AI-skill advertisements in {YEAR}; "
    "repeat postings of the same advertisement are counted once. Rows do not sum to 100: "
    "the remainder is advertisements the classifier places in the AI-literacy grey zone or "
    "judges not to be AI demand at all, which is how medical secretaries appear at zero on "
    "all three tiers despite passing the lexical measure."
)


def main():
    prev = yaml.safe_load(OUT.read_text(encoding="utf-8")) if OUT.exists() else {}

    rows, dropped = [], []
    for r in csv.DictReader(SRC.open(encoding="utf-8")):
        if r["year"] != YEAR or not r["label"]:
            continue
        n = int(r["n"])
        name = EN.get(r["label"], r["label"])
        entry = {"name": name}
        # Written down only when the official title is too long to print, so a name_short line
        # here reads as "that one was shortened". See _row() in refresh_occupations.py for why
        # a derived column is stored at all, and check_label_columns.py for what stops it
        # drifting away from labels.shorten().
        if shorten(name) != name:
            entry["name_short"] = shorten(name)
        entry.update({"n": n,
                      "builder": round(100 * int(r["builder"]) / n),
                      "integrator": round(100 * int(r["integrator"]) / n),
                      "user": round(100 * int(r["user"]) / n)})
        (rows if n >= MIN_ADS else dropped).append(entry)

    rows.sort(key=lambda x: -x["n"])

    doc = {
        "meta": {
            "year": int(YEAR),
            "min_ads": MIN_ADS,
            "source": "JobTech / Platsbanken job ads (CC0) · tier classifier, rubric v2.1 · "
                      "distinct advertisements",
            "validation": prev.get("meta", {}).get(
                "validation",
                "88.9% agreement with hand-labelled ads on the four-way split, 93.8% on the "
                "grouping shown"),
        },
        "lede": prev.get("lede", ""),
        "rows": rows,
        "caveat": CAVEAT,
    }
    OUT.write_text("# Generated by scripts/refresh_occupation_tiers.py. Do not hand-edit.\n"
                   + yaml.dump(doc, allow_unicode=True, sort_keys=False, width=95),
                   encoding="utf-8")
    print(f"occupation_tiers.yaml: {YEAR}, {len(rows)} occupations with >= {MIN_ADS} "
          f"distinct advertisements")
    if dropped:
        near = sorted((d for d in dropped if d["n"] >= MIN_ADS - 5), key=lambda x: -x["n"])
        print(f"  below the threshold and therefore not shown: "
              + ", ".join(f"{d['name']} ({d['n']})" for d in near))
    unlisted = [r["name"] for r in rows if r["name"] not in EN.values()]
    if unlisted:
        print(f"  NO ENGLISH NAME, showing the Swedish label: {', '.join(unlisted)}")


if __name__ == "__main__":
    main()
